apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fsrx42d5r-python 
  janus-idp.io/tekton: fsrx42d5r-python
  backstage.io/kubernetes-id: fsrx42d5r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fsrx42d5r-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml